name: node js apploication
on: workflow_dispatch
jobs:
   job1:
    stratergy: 
      matrix:
       node-version: [18]
       operating-system: [ubuntu-latest, windows-latest]
    runs-on: 4{{ matrix.operating-system}}
    steps: 
      - name: clone the apploication
        uses: action/checkout@4
      - name: Install node.js
        uses: action/setup-node@v4
        with: 
            node-version: ${{ matrix.node-version}}
            cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: execute test cases
        run: npm test
